# Generated by Django 5.2.6 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'db_table': 'services_categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción de los servicios que ofrece')),
                ('resume', models.FileField(help_text='Hoja de vida (PDF o imagen)', upload_to='services/resumes/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestador de Servicio',
                'verbose_name_plural': 'Prestadores de Servicio',
                'db_table': 'services_providers',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción del trabajo requerido')),
                ('status', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='REGISTRADA', max_length=20)),
                ('provider_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('runners_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'db_table': 'services_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
