# Generated by Django 5.2.6 on 2026-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil del prestador', null=True, upload_to='services/providers/photos/'),
        ),
    ]
