# Generated by Django 5.2.6 on 2026-05-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprovider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='services.servicecategory'),
        ),
    ]
