# Generated by Django 5.2.6 on 2026-03-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='deliverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to='deliveries.deliverer'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='deliverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='deliveries.deliverer'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='related_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='deliveries.deliveryrequest'),
        ),
    ]
