# Generated by Django 5.2.6 on 2026-03-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='deliverer',
            field=models.ForeignKey(blank=True, help_text='Se asigna automáticamente al crear la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to='deliveries.deliverer'),
        ),
    ]
