# Generated by Django 5.2.6 on 2026-04-03 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryrequest_completed_at_and_more'),
        ('store', '0003_commerce_business_type_commerce_menu_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('request_kind', models.CharField(choices=[('RECOGER_ENTREGAR', 'Recoger y Entregar'), ('COMPRA_SENCILLA', 'Compra Sencilla'), ('SUPERMERCADO', 'Supermercado'), ('MULTIPUNTO', 'Multipunto')], max_length=30)),
                ('min_items', models.PositiveIntegerField(blank=True, null=True)),
                ('max_items', models.PositiveIntegerField(blank=True, null=True)),
                ('min_points', models.PositiveIntegerField(blank=True, null=True)),
                ('max_points', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Tarifa',
                'verbose_name_plural': 'Reglas de Tarifas',
                'db_table': 'deliveries_pricing_rules',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de Domicilio',
                'verbose_name_plural': 'Zonas de Domicilio',
                'db_table': 'deliveries_zones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='associated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='association_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='commerce',
            field=models.ForeignKey(blank=True, help_text='Negocio asociado al domicilio cuando aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='store.commerce'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='is_transfer_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='items_count',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad estimada de productos'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='points_count',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de puntos/establecimientos del recorrido'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='product_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='request_kind',
            field=models.CharField(choices=[('RECOGER_ENTREGAR', 'Recoger y Entregar'), ('COMPRA_SENCILLA', 'Compra Sencilla'), ('SUPERMERCADO', 'Supermercado'), ('MULTIPUNTO', 'Multipunto')], default='RECOGER_ENTREGAR', max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='source_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('STORE', 'Desde Tienda')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='transfer_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='affects_balance',
            field=models.BooleanField(default=True, help_text='Si está activo, afecta el balance del domiciliario (INGRESO - EGRESO).'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='classification',
            field=models.CharField(choices=[('NEGRO', 'Transacción Normal'), ('ROJO', 'Deuda a favor del Domiciliario'), ('AZUL', 'Saldo Extra en Caja del Domiciliario')], default='NEGRO', max_length=10),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='reason',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('DOMICILIO', 'Domicilio'), ('RECARGO_TRANSFERENCIA', 'Recargo por Transferencia (Runners)'), ('CONSIGNACION_BASE', 'Consignación de Base'), ('COBRO_DEUDA_CLIENTE', 'Cobro de Deuda de Cliente'), ('AJUSTE_MANUAL', 'Ajuste Manual')], default='AJUSTE_MANUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryCommerceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_history', to='deliveries.deliveryrequest')),
                ('new_commerce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.commerce')),
                ('previous_commerce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.commerce')),
            ],
            options={
                'verbose_name': 'Historial de Asociación de Negocio',
                'verbose_name_plural': 'Historial de Asociación de Negocio',
                'db_table': 'deliveries_commerce_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='deliveries.deliverypricingrule'),
        ),
        migrations.AddField(
            model_name='deliverypricingrule',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, aplica para cualquier zona.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='deliveries.deliveryzone'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='deliveries.deliveryzone'),
        ),
    ]
