# Generated by Django 5.2.6 on 2026-05-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_merge_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='associated_by',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='association_notes',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pricing_rule',
        ),
    ]
