# Generated by Django 5.2.6 on 2026-05-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_remove_deliveryrequest_associated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Marca cuando se asignó un domiciliario candidato.', null=True),
        ),
    ]
