# Generated by Django 5.2.6 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('contact_type', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('PROFESIONAL', 'Profesional'), ('COMERCIO', 'Comercio'), ('OTRO', 'Otro')], default='PROFESIONAL', max_length=20)),
                ('availability', models.CharField(choices=[('EN_SERVICIO', 'En Servicio'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio')], default='EN_SERVICIO', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacts',
                'ordering': ['contact_type', 'name'],
            },
        ),
    ]
