# Generated by Django 5.2.6 on 2026-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_approval_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('PROFESIONAL', 'Profesional'), ('COMERCIO', 'Comercio'), ('CONTACTO', 'Contacto'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], default='PROFESIONAL', max_length=20),
        ),
    ]
