# Generated by Django 5.2.6 on 2026-04-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_commerce_menu_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('TIENDA', 'Tienda'), ('FARMACIA', 'Farmacia'), ('SUPERMERCADO', 'Supermercado'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
