# Generated by Django 5.2.6 on 2026-05-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceMenuFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='store/menus/')),
                ('file_type', models.CharField(blank=True, choices=[('IMAGE', 'Imagen'), ('PDF', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_files', to='store.commerce')),
            ],
            options={
                'verbose_name': 'Archivo de Carta',
                'verbose_name_plural': 'Archivos de Carta',
                'db_table': 'store_commerce_menu_files',
            },
        ),
    ]
